# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Pipeline.Workspace)'
    Contents: '**/target/*.?(jar|war)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true
    
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'public-search-service-mx'
    publishLocation: 'pipeline'
- task: AzureAppServiceSettings@1
  inputs:
    azureSubscription: 'BEIS_COG_Subsidy_Control_Transparency_DB(8e9969b3-7574-441c-a10f-7114dc3314f7)'
    appName: 'dev-transparency-db-publicsearch-portal'
    resourceGroupName: 'BEIS-DEV-RG'
    appSettings: |
      {
          "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
          "contentVersion": "1.0.0.0",
          "parameters": {
              "subscriptionId": {
                  "type": "string"
              },
              "name": {
                  "type": "string"
              },
              "location": {
                  "type": "string"
              },
              "hostingPlanName": {
                  "type": "string"
              },
              "serverFarmResourceGroup": {
                  "type": "string"
              },
              "alwaysOn": {
                  "type": "bool"
              },
              "linuxFxVersion": {
                  "type": "string"
              }
          },
          "resources": [
              {
                  "apiVersion": "2018-11-01",
                  "name": "[parameters('name')]",
                  "type": "Microsoft.Web/sites",
                  "location": "[parameters('location')]",
                  "tags": {},
                  "dependsOn": [],
                  "properties": {
                      "name": "[parameters('name')]",
                      "siteConfig": {
                          "appSettings": [],
                          "linuxFxVersion": "[parameters('linuxFxVersion')]",
                          "alwaysOn": "[parameters('alwaysOn')]"
                      },
                      "serverFarmId": "[concat('/subscriptions/', parameters('subscriptionId'),'/resourcegroups/', parameters('serverFarmResourceGroup'), '/providers/Microsoft.Web/serverfarms/', parameters('hostingPlanName'))]",
                      "clientAffinityEnabled": false
                  }
              }
          ]
      }
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'BEIS_COG_Subsidy_Control_Transparency_DB(8e9969b3-7574-441c-a10f-7114dc3314f7)'
    appType: 'webAppLinux'
    WebAppName: 'dev-transparency-db-public-search-service'
    deployToSlotOrASE: true
    ResourceGroupName: 'BEIS-DEV-RG'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'TOMCAT|9.0-jre8'