# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pr:
  - master

variables:

  # Agent VM image name
  vmImageName: 'ubuntu-20.04'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: MavenBuild
        displayName: Maven Package and Publish Artifacts
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Maven@3
            displayName: 'Maven Package'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
              goals: 'package spring-boot:repackage'
          - task: CopyFiles@2
            displayName: 'Copy Files to artifact staging directory'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/target'
              Contents: '*.?(war|jar)'
              TargetFolder: $(Build.ArtifactStagingDirectory)
          - task: PublishPipelineArtifact@1
            displayName: 'Publish pipeline artifacts'
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)

  - stage:
    displayName: Deploy to dev/test environment
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - job: waitForValidation
        displayName: Confirm dev/test deployment
        pool: server    
        timeoutInMinutes: 4320 # job times out in 3 days
        steps:   
        - task: ManualValidation@0
          timeoutInMinutes: 1440 # task times out in 1 day
          inputs:
              instructions: 'Please confirm deployment to dev/test'
      - deployment: DeployLinuxWebAppDev
        displayName: Deploy Linux Web App - TestDev
        environment: 'dev'
        dependsOn: waitForValidation
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Bash@3
                  inputs:
                    targetType: 'inline'
                    script: 'mv $(Pipeline.Workspace)/Build.MavenBuild/*.jar $(Pipeline.Workspace)/app.jar'
                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'BEIS-Subsidy-Control-TestDev'
                    appType: 'webAppLinux'
                    WebAppName: 'dev-transparency-db-public-search-service'
                    packageForLinux: '$(Pipeline.Workspace)/app.jar'
  - stage:
    displayName: Deploy to staging environment
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - deployment: DeployLinuxWebAppStg
        displayName: Deploy Linux Web App - Staging
        environment: 'stg'
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Bash@3
                  inputs:
                    targetType: 'inline'
                    script: 'mv $(Pipeline.Workspace)/Build.MavenBuild/*.jar $(Pipeline.Workspace)/app.jar'
                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'BEIS-Subsidy-Control-Staging'
                    appType: 'webAppLinux'
                    WebAppName: 'stg-transparency-db-public-search-service'
                    packageForLinux: '$(Pipeline.Workspace)/app.jar'