INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Historic Environment Scotland');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'HMRC');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Museum Galleries Scotland');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'OFGEM');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Scottish Government');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'South Ayrshire Council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Transport Scotland');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'BFI');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Somerset County Council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Chesterfield council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Derby');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Dorset LEP');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'AHDB');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Gateshead Council ');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Keele');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'The Trustees of the National Heritage Memorial Fund');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Dover');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'University of Newcastle');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Highlands & Islands Enterprise');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Enfield');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Oxfordshire County Council');
INSERT INTO GRANTING_AUTHORITY (GA_ID, GA_NAME) VALUES(nextval('granting_authority_read_seq'),'Worcestershire');