INSERT INTO LEGAL_BASIS (LEGAL_BASIS_ID, SC_NUMBER, LEGAL_BASIS_TEXT) VALUES(nextval('legal_basis_seq'), 'SC10000','R&D&I Framework');
INSERT INTO LEGAL_BASIS (LEGAL_BASIS_ID, SC_NUMBER, LEGAL_BASIS_TEXT) VALUES(nextval('legal_basis_seq'),'SC10029','R&D&I Framework');

INSERT INTO LEGAL_BASIS (LEGAL_BASIS_ID, SC_NUMBER, LEGAL_BASIS_TEXT) VALUES(nextval('legal_basis_seq'), 'SC10001','Corporation Tax Act 2009');
INSERT INTO LEGAL_BASIS (LEGAL_BASIS_ID, SC_NUMBER, LEGAL_BASIS_TEXT) VALUES(nextval('legal_basis_seq'), 'SC10002','R&D&I Framework');
INSERT INTO LEGAL_BASIS (LEGAL_BASIS_ID, SC_NUMBER, LEGAL_BASIS_TEXT) VALUES(nextval('legal_basis_seq'), 'SC10003','Culturally British and European high-end television programmes');
INSERT INTO LEGAL_BASIS (LEGAL_BASIS_ID, SC_NUMBER, LEGAL_BASIS_TEXT) VALUES(nextval('legal_basis_seq'),'SC10004','Local Government in Scotland Act 2003');
INSERT INTO LEGAL_BASIS (LEGAL_BASIS_ID, SC_NUMBER, LEGAL_BASIS_TEXT) VALUES(nextval('legal_basis_seq'),'SC10005','Section 100 of the Energy Act 2008');
INSERT INTO LEGAL_BASIS (LEGAL_BASIS_ID, SC_NUMBER, LEGAL_BASIS_TEXT) VALUES(nextval('legal_basis_seq'),'SC10006','R&D&I Framework');
INSERT INTO LEGAL_BASIS (LEGAL_BASIS_ID, SC_NUMBER, LEGAL_BASIS_TEXT) VALUES(nextval('legal_basis_seq'),'SC10007','R&D&I Framework');
INSERT INTO LEGAL_BASIS (LEGAL_BASIS_ID, SC_NUMBER, LEGAL_BASIS_TEXT) VALUES(nextval('legal_basis_seq'),'SC10009','R&D&I Framework');
INSERT INTO LEGAL_BASIS (LEGAL_BASIS_ID, SC_NUMBER, LEGAL_BASIS_TEXT) VALUES(nextval('legal_basis_seq'),'SC10011','R&D&I Framework');

--------------------------------------------------------
--1.0 BENEFICIARY - Insert scripts
--------------------------------------------------------
INSERT INTO public.BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'Aberdeen City Heritage Trust','Company','SC271933','Company Registration Number','74909','Small Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'ABSOLEM PRODUCTIONS LIMITED','Company','2138921801','Company Registration Number','59111','Large Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'1E LIMITED','Company','3180711904','Company Registration Number','62090','Small Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'4D PHARMA RESEARCH LIMITED','Company','SC336222','Company Registration Number','72110','Small Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'8BUILD LIMITED','Company','5523722','Company Registration Number','41201','Small Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'ABSOLEM PRODUCTIONS LIMITED','Company','2138921801','Company Registration Number','59111','Large Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'ABSOLEM PRODUCTIONS LIMITED','Company','2138921801','Company Registration Number','59111','Large Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'ADAMAARKU PRODUCTIONS LTD','Company','10855337','Company Registration Number','59111','Medium Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'ADAMAARKU PRODUCTIONS LTD','Company','10855337','Company Registration Number','59111','Medium Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'Alford and Donside Heritage Association','Company','SC020212','Charity Number','','Small Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'Almond Valley Heritage Trust','Company','SC013783','Charity Number','84120','Medium Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'Adam Wilson & Sons Ltd','Company','SC230058','Company Registration Number','70100','Medium Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'Adam Wilson & Sons Ltd','Company','SC230058','Company Registration Number','70100','Medium Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'A W Jenkinson Forest Products','Company','3103092','Company Registration Number','74990','Small Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'A. Y. BRAILSFORD','Company','B13943','Company Registration Number','52220','Micro Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'A&C Tait','Company','SB0407','Company Registration Number','43310','Micro Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'A&C Tait','Company','SB0407','Company Registration Number','43310','Micro Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'Almond Park Nursery Ltd','Company','SC460896','Company Registration Number','88910','Small Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'Acrewood Nursery Ltd','Company','SC231967','Company Registration Number','88910','Small Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'ABC Day Nursery','Company','SC229641','Company Registration Number','85100','Micro Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'AdelSubsidye Place Development Company Ltd','Company','SC142177','Company Registration Number','85100','Medium Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'Alphabet Village Ltd','Company','SC270780','Company Registration Number','','Micro Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'Abriachan Forest Trust','Company','SC025690','Charity Number','02100 ,  85600','Medium Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'ACE Playgroup & Busy Bees','Company','1032318','Charity Number','81210','Medium Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'Aberfoyle Out of School CLub','Company','SC432515','Company Registration Number','88910','Micro Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'Aberfoyle Too','Company','','Company Registration Number','1300','Micro Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'ABC Tots','Company','SC248359','Company Registration Number','88910','Micro Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'ABBEY MILL CHILDCARE LTD','Company','SC259017','Company Registration Number','85590','Micro Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'ABC Nursery Above & Beyond Childcare','Company','SC543850','Company Registration Number','82990','Micro Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'3 Bears Nursery Limited','Company','SC250276','Company Registration Number','85100','Micro Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'Aberdeen Step by Step Nursery Ltd','Company','SC291171','Company Registration Number','85100','Micro Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'Alford Playgroup','Company','SC021981','Charity Number','88910','Small Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'Aberlour Child care Trust Family centre Langlees','Company','SC007991','Charity Number','','Large Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'ABC Nursery','Company','SC279352','Company Registration Number','85100; 88910','Micro Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'A1 Ironmongery Limited','Company','SC412412','Company Registration Number','46740','Micro Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'24/7 CARS LLP','Company','SO300247','Company Registration Number','','Micro Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'24/7 CARS LLP','Company','SO300247','Company Registration Number','','Micro Organisation');
INSERT INTO BENEFICIARY(BENEFICIARY_ID, BENEFICIARY_NAME, BENEFICIARY_TYPE, NATIONAL_ID, NATIONAL_ID_TYPE,SIC_CODE, SIZE_OF_ORG) VALUES (nextval('BENEFICIARY_seq'),'A & J BALLANTYNE','Company','SC576466','Company Registration Number','49390','Micro Organisation');
--------------------------------------------------------
commit;



INSERT INTO AWARD
(AWARD_NUMBER, SC_NUMBER, GA_ID, BENEFICIARY_ID,
SUBSIDY_ELEMENT_FULL_AMOUNT_RANGE, SUBSIDY_ELEMENT_FULL_AMOUNT_EXACT, SUBSIDY_OBJECTIVE, GOOD_SERVICES_FILTER,
LEGAL_GRANTING_DATE, PUBLISHED_AWARD_DATE, SPENDING_REGION, SUBSIDY_INSTRUMENT, SPENDING_SECTOR,STATUS)
VALUES(nextval('award_seq'),'SC10000',43,1,'> 5000000 - 10000000',0,'Culture/Heritage','','2016-08-02',
'2017-12-11','LONDON','Other - Form of tax advantage','information and communication','Finalised');

INSERT INTO AWARD
(AWARD_NUMBER, SC_NUMBER, GA_ID, BENEFICIARY_ID,
SUBSIDY_ELEMENT_FULL_AMOUNT_RANGE, SUBSIDY_ELEMENT_FULL_AMOUNT_EXACT, SUBSIDY_OBJECTIVE, GOOD_SERVICES_FILTER,
LEGAL_GRANTING_DATE, PUBLISHED_AWARD_DATE, SPENDING_REGION, SUBSIDY_INSTRUMENT, SPENDING_SECTOR, STATUS)
VALUES(nextval('award_seq'),'SC10001',49,1,'500000 - 1000000',0,'Research and development','Services','2016-10-10','2018-01-19','LONDON','Tax measures (tax credit, or tax/duty exemption)','information and communication','Published');
INSERT INTO AWARD
(AWARD_NUMBER, SC_NUMBER, GA_ID, BENEFICIARY_ID,
SUBSIDY_ELEMENT_FULL_AMOUNT_RANGE, SUBSIDY_ELEMENT_FULL_AMOUNT_EXACT, SUBSIDY_OBJECTIVE, GOOD_SERVICES_FILTER,
LEGAL_GRANTING_DATE, PUBLISHED_AWARD_DATE, SPENDING_REGION, SUBSIDY_INSTRUMENT, SPENDING_SECTOR, STATUS)
VALUES(nextval('award_seq'),'SC10002',50,1,'500000 - 1000000',0,'Research and development','Services','2016-11-12','2018-02-21','SCOTLAND','Tax measures (tax credit, or tax/duty exemption)','professional, scientific and technical activities','Rejected');
INSERT INTO AWARD
(AWARD_NUMBER, SC_NUMBER, GA_ID, BENEFICIARY_ID,
SUBSIDY_ELEMENT_FULL_AMOUNT_RANGE, SUBSIDY_ELEMENT_FULL_AMOUNT_EXACT, SUBSIDY_OBJECTIVE, GOOD_SERVICES_FILTER,
LEGAL_GRANTING_DATE, PUBLISHED_AWARD_DATE, SPENDING_REGION, SUBSIDY_INSTRUMENT, SPENDING_SECTOR, STATUS)
VALUES(nextval('award_seq'),'SC10003',51,1,'500000 - 1000000',0,'Research and development','Services','2016-12-20','2018-02-21','LONDON','Tax measures (tax credit, or tax/duty exemption)','construction','Finalised');


